# service:
#   port: ':8080'
#   secretJWT: 'superSecretJwt'

# database:
#   dataSourceName: 'root:superSecretPassword@tcp(localhost:3306)/ifortepay_hometest?parseTime=true'

service:
  port: ':8080'
  secretJWT: 'superSecretJwt'

database:
  dataSourceName: '${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/${DB_NAME}?parseTime=true'
