CREATE TABLE IF NOT EXISTS  products (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  sku VARCHAR(10) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  inventory_qty INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);